### ISSUE TITLE
Opción explícita de copiar link en sala de espera

### ISSUE THREAD

**Issue by Dih5** [PlushyZeus35/PlusLearn#50]
En la sala de espera del admin, además del QR podría darse una opción para compartir el link tal cual. Es verdad que es el mismo de la página activa, pero una opción para copiarlo al portapapeles es conveniente y puede facilitar la experiencia de usuario.

**Comment by PlushyZeus35** [comment]
Botón añadido a la sala de espera para poder copiar el enlace del cuestionario directamente.
