### ISSUE TITLE
Color en gráficos

### ISSUE THREAD

**Issue by Dih5** [PlushyZeus35/PlusLearn#51]
En los gráficos que se muestran con las respuestas a cada pregunta, podría ser más claro que se muestre en color verde la barra correspondiente a una respuesta correcta y rojo las de las incorrectas.

**Comment by PlushyZeus35** [comment]
Se ha decidido mostrar por cada pregunta el número de respuestas correctas, incorrectas y sin responder con el código de colores correspondiente. Además de mostrar la leyenda del gráfico para permitir al usuario esconder un tipo de respuesta si lo prefiere. 
![image](https://github.com/PlushyZeus35/PlusLearn/assets/45199219/ff295883-e298-4504-873a-a4e0cc54f647)

**Comment by PlushyZeus35** [comment]
Se han coloreado las opciones en las tablas de estadísticas de preguntas para diferenciar claramente la respuesta correcta de las demás.
![image](https://github.com/PlushyZeus35/PlusLearn/assets/45199219/f1c31fbf-a132-48b8-acd1-13e7103a26af)
