### ISSUE TITLE
Información adicional en recuperación de cuenta

### ISSUE THREAD

**Issue by Dih5** [PlushyZeus35/PlusLearn#54]
En el formulario de recuperación, no se muestra información cuando ocurren errores (al intentar recuperar una cuenta inexistente o al escribir mal el código de recuperación, al dejar en blanco la contraseña).

**Comment by PlushyZeus35** [comment]
Realizados mensajes cuando no se encuentra usuario, cuando se introduce un codigo incorrecto y cuando no se introduce nueva contraseña o es inválida
